server:
  port: 8399
  servlet:
    jsp:
      init-parameters:
        development: true
  tomcat:
    connection-timeout: 60m     # 60분 동안 연결 유지
    max-threads: 200            # 비동기 요청 처리를 위한 쓰레드 개수 증가

spring:
  # Oracle Connect
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@1.234.5.72:1521/xe
    username: s202501b
    password: tiger
  
  # File Size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  
  # JPA Setting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create

  # View Resolver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  
  # gmail Transfer (OSI7 -> Application) --> SMTP (FTP, SMTP, TELNET)
  mail:
    host: smtp.gmail.com
    port: 587
    username: 0808hr@gmail.com
    password: xgpnubrvrmraahiy
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true  
                        
#Mybatis
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml

  
#jwt
jwt:
  secret: f3d5dcfa8c3499bbeeebba5264de4f66b73e449ccbd442b8cde1ba639dc2d63c
  access-token-expiration: 120000  #2분
  refresh-token-expiration: 86400000 #하루
 
#kakao
kakao:
  client:
    id: efe8479005b06cbc1480277bd66620d9
  redirect:
    uri: http://localhost:8399/oauth/api/kakao
  admin-key: 3e2778273943c7234e9b0fc8bcf90f4d
  
  
  
  
  